//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/components.tpa"
INCLUDE "%WEIDU_LIBRARY_DIR%/installers.tpa"


//Initialization.
LAF get_component_root RET root = dir END
LAF get_component_resources_dir RET resources = dir END
LAF get_component_tra_dir RET tra = dir END


//Install subspells for items.
LAF install_resources STR_VAR
    type = "subspell"
    table = "%resources%/2da/subspells.2da"
    patches = "%root%/patches/subspells.tpa"
    tra = "%tra%/subspells.tra"
END
