INCLUDE ~spell_rev\lib\cre_spell_immunity.tph~
INCLUDE ~spell_rev\lib\manage_add_spell_references.tpa~


/*------------Manage ADD_SPELL References, Part 1-----------*/

// Spells that will be installed with ADD_SPELL have an unknown final filename.
// If any SPL/ITM/EFF files need to reference those new spells, they can do so using their current filenames in the mod folder.
// This function will go through those files and replace the references to current filenames with temp filenames.
LAF ASSIGN_TEMP_NAMES_FOR_NEW_SPELL_REFERENCES END


/* ----Various---- */

// SD: eliminate #bonecir.spl from IWDEE
ACTION_IF GAME_IS ~iwdee~ BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~#bonecir.spl~ BEGIN
	  DISABLE_FROM_KEY ~#bonecir.spl~
  END
  ACTION_IF FILE_EXISTS ~override/#bonecir.spl~ BEGIN
	  DELETE ~override/#bonecir.spl~
  END
END

// IWDEE AI can't effectively use SR's Cause Wounds spells
// Until this is resolved, the spells won't be installed on IWDEE
OUTER_SET install_cause_wounds = NOT GAME_IS ~iwdee~

// Scroll Of Restoration: no longer needed since addition of spellbook fixing code in v3
// adscroll.itm still copied over in case someone wants to CLUAConsole it for use on an old save game
COPY ~spell_rev\shared\adscroll.itm~     ~override~
  SAY NAME2 @22000    SAY IDENTIFIED_DESC   @22001
COPY ~spell_rev\shared\adscroll.bam~     ~override~

COPY ~spell_rev\shared\dvimhere.mrk~      ~override~  // Used to detect if SR is installed
COPY ~spell_rev\shared\dvsrv3.mrk~      ~override~  // Used to detect if SR V3 is installed
COPY ~spell_rev\shared\dvsrv4here.mrk~      ~override~  // Used to detect if SR V4 is installed

STRING_SET ~27982~ @5410 // replaces 'Protection from Illusions removed' with 'Illusionary protections removed'
// STRING_SET ~34560~ @6670 // replaces 'Battleground Effects Removed' with 'Petrification effects reverted'

STRING_SET ~8275~ @105 // replaces 'Repulsing Undead' with 'Repulsion'

STRING_SET ~12122~ @49 // replaces 'Resist Fire and Cold' with 'Resist Elements'
STRING_SET ~17417~ @49 // replaces 'Resist Fire/Cold' with 'Resist Elements'

COPY_EXISTING ~intmod.2da~ ~override~  // Int Modifier for Maze & Imprisonment
  SET_2DA_ENTRY 0 4 6 ~7200~
  SET_2DA_ENTRY 0 5 6 ~1~
  SET_2DA_ENTRY 1 4 6 ~7200~
  SET_2DA_ENTRY 1 5 6 ~1~
  SET_2DA_ENTRY 2 4 6 ~7200~
  SET_2DA_ENTRY 2 5 6 ~1~
  SET_2DA_ENTRY 3 4 6 ~10~
  SET_2DA_ENTRY 3 5 6 ~4~
  SET_2DA_ENTRY 4 4 6 ~10~
  SET_2DA_ENTRY 4 5 6 ~4~
  SET_2DA_ENTRY 5 4 6 ~10~
  SET_2DA_ENTRY 5 5 6 ~4~
  SET_2DA_ENTRY 6 4 6 ~5~
  SET_2DA_ENTRY 6 5 6 ~4~
  SET_2DA_ENTRY 7 4 6 ~5~
  SET_2DA_ENTRY 7 5 6 ~4~
  SET_2DA_ENTRY 8 4 6 ~5~
  SET_2DA_ENTRY 8 5 6 ~4~
  PRETTY_PRINT_2DA
  BUT_ONLY_IF_IT_CHANGES

COPY ~spell_rev\shared\contingx.2da~      ~override~  // spells used for contingencies

COPY ~spell_rev\shared\dvbanish.eff~     ~override~ // Banish EFFs
COPY ~spell_rev\shared\dvbanish.spl~     ~override~

COPY ~spell_rev\shared\dvpowerw.eff~     ~override~ // Power Words vvc

COPY ~spell_rev\shared\dvelair.vvc~     ~override~ // Conjure Air Elemental new animation
COPY ~spell_rev\shared\dvelair.bam~     ~override~
COPY ~spell_rev\shared\dveleart.vvc~     ~override~ // Conjure Earth Elemental new animation
COPY ~spell_rev\shared\dveleart.bam~     ~override~
COPY ~spell_rev\shared\dvelfire.vvc~     ~override~ // Conjure Fire Elemental new animation
COPY ~spell_rev\shared\dvelfire.bam~     ~override~

COPY ~spell_rev\shared\illush.wav~      ~override~  // New illusion spell effect
COPY ~spell_rev\shared\illush.bam~      ~override~
COPY ~spell_rev\shared\illushvc.vvc~      ~override~

COPY ~spell_rev\shared\spmagglo.vvc~     ~override~ // New Spell Deflection/Immunity animation
COPY ~spell_rev\shared\spmagglo.bam~     ~override~

COPY ~spell_rev\shared\dvsun1.vvc~      ~override~  // New sunlight effect
COPY ~spell_rev\shared\dvsun2.vvc~      ~override~
COPY ~spell_rev\shared\dvsun.bam~      ~override~

COPY ~spell_rev\shared\dvinvis.spl~      ~override~  // Invisibility
COPY ~spell_rev\shared\spwi977.spl~      ~override~  // Shapeshift Natural Form
COPY ~spell_rev\shared\spwi978.spl~      ~override~  // Shapeshift Natural Form

COPY ~spell_rev\shared\wings~      ~override~  // 1PP attachable wings

COPY ~spell_rev\shared\unddeath.eff~     ~override~ // Variant undead death effect

COPY ~spell_rev\shared\dvtsight.eff~     ~override~ // Highlight illusionary creatures
COPY ~spell_rev\shared\dvtsight.spl~     ~override~


/* ----Projectiles---- */

ADD_PROJECTILE ~spell_rev\projectles\dvmainpr.pro~ // 1 target, no animation, 200 speed

COPY_EXISTING ~bignarea.pro~ ~override~
  WRITE_SHORT 0x206 450
  BUT_ONLY_IF_IT_CHANGES
  
COPY_EXISTING ~iceglyp.pro~ ~override~  // Symbol of Death/Stun/Weakness
  WRITE_SHORT 0x200 77  // Don't affect caster and allied creatures
  WRITE_SHORT 0x206 200
  BUT_ONLY_IF_IT_CHANGES
  
COPY_EXISTING ~trapglyp.pro~ ~override~  // Fire Trap/Glyph of Warding
  WRITE_SHORT 0x200 77  // Don't affect caster and allied creatures
  WRITE_SHORT 0x206 200
  BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING ~spklargr.pro~ ~override~ // Dispel Magic
  WRITE_SHORT 0x206 190  // Reduced AoE to 20'
  BUT_ONLY_IF_IT_CHANGES
  
COPY_EXISTING ~spargrnp.pro~ ~override~ // Remove Magic
  WRITE_SHORT 0x206 190  // Reduced AoE to 20'
  BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING ~inareasm.pro~ ~override~
  WRITE_SHORT 0x206 110
  BUT_ONLY_IF_IT_CHANGES
  
COPY_EXISTING ~newbolt1.pro~ ~override~  // Lightning Bolt's "new" projectile
  WRITE_SHORT 0x0a 30  // Increase speed to 30
  BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING ~lightcha.pro~ ~override~  // Chain Lightning projectile
  WRITE_SHORT 0x0a 30  // Increase speed to 30
  BUT_ONLY_IF_IT_CHANGES
  
COPY_EXISTING ~smllarnc.pro~ ~override~
  WRITE_SHORT 0x206 65
  WRITE_SHORT 0x206 65
  BUT_ONLY_IF_IT_CHANGES
  
COPY_EXISTING ~smllnpc.pro~ ~override~
  WRITE_SHORT 0x206 65
  WRITE_SHORT 0x206 65
  BUT_ONLY_IF_IT_CHANGES
  
COPY_EXISTING ~hold.pro~ ~override~ // Hold
  WRITE_SHORT 0x206 65
  WRITE_SHORT 0x206 65
  BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING ~holdnecr.pro~ ~override~ // Halt/Control Undead
  WRITE_SHORT 0x206 65
  WRITE_SHORT 0x206 65
  BUT_ONLY_IF_IT_CHANGES
  
COPY_EXISTING ~insec2.pro~ ~override~  // Insect Plague and Creeping Doom
  WRITE_SHORT 0x0a 10  // Increase speed to 10 to match Sumon Insect's one 
  BUT_ONLY_IF_IT_CHANGES
  
COPY_EXISTING ~metswarm.pro~ ~override~  // Firestorm and vanilla's Meteor Swarm
  WRITE_SHORT 0x0a 40  // Increase speed to 40
  WRITE_BYTE 0x216 4  // Fix duration to 4 rounds
  BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING ~dfirebl.pro~  ~override~  // Trap-like projectiles trigger more quickly
              ~iceglyp.pro~  ~override~
              ~trapglyp.pro~ ~override~
              ~trapskul.pro~ ~override~
  WRITE_SHORT 0x210 10
  BUT_ONLY_IF_IT_CHANGES


/* ----Improved AI---- */

COPY ~spell_rev\shared\dvmelee.bcs~     ~override~  // Summons' melee AI
COPY ~spell_rev\shared\dvranged.bcs~     ~override~  // Summons' ranged AI
COPY ~spell_rev\shared\dvbrsker.bcs~     ~override~  // Summons' melee AI (with berserking ability)


/* ----Creature Type Characteristics---- */

COPY ~spell_rev\shared\elemtype.itm~     ~override~  // Elemental type characteristics
COPY ~spell_rev\shared\undtype.itm~     ~override~  // Undead type characteristics
COPY ~spell_rev\shared\vermtype.itm~     ~override~  // Vermin type characteristics


/* ----Bhaalspawn Abilities---- */

ACTION_IF FILE_EXISTS_IN_GAME ~spin101.spl~ BEGIN
  COPY_EXISTING ~spin101.spl~ ~override~
	READ_LONG 0x8 spl_name
	READ_LONG 0x50 spl_desc
COPY ~spell_rev\shared\spin101.spl~     ~override~ // Cure Light Wounds
	WRITE_LONG 0x8 spl_name
	WRITE_LONG 0x50 spl_desc
END
ACTION_IF FILE_EXISTS_IN_GAME ~spin102.spl~ BEGIN
  COPY_EXISTING ~spin102.spl~ ~override~
	READ_LONG 0x8 spl_name
	READ_LONG 0x50 spl_desc
COPY ~spell_rev\shared\spin102.spl~     ~override~ // Slow Poison
	WRITE_LONG 0x8 spl_name
	WRITE_LONG 0x50 spl_desc
END
ACTION_IF FILE_EXISTS_IN_GAME ~spin103.spl~ BEGIN
  COPY_EXISTING ~spin103.spl~ ~override~
	READ_LONG 0x8 spl_name
	READ_LONG 0x50 spl_desc
COPY ~spell_rev\shared\spin103.spl~     ~override~ // Draw upon Divine Might
	WRITE_LONG 0x8 spl_name
	WRITE_LONG 0x50 spl_desc
END
ACTION_IF FILE_EXISTS_IN_GAME ~spin104.spl~ BEGIN
  COPY_EXISTING ~spin104.spl~ ~override~
	READ_LONG 0x8 spl_name
	READ_LONG 0x50 spl_desc
COPY ~spell_rev\shared\spin104.spl~     ~override~ // Larloch's Minor Drain
	WRITE_LONG 0x8 spl_name
	WRITE_LONG 0x50 spl_desc
END
ACTION_IF FILE_EXISTS_IN_GAME ~spin105.spl~ BEGIN
  COPY_EXISTING ~spin105.spl~ ~override~
	READ_LONG 0x8 spl_name
	READ_LONG 0x50 spl_desc
COPY ~spell_rev\shared\spin105.spl~     ~override~ // Horror
	WRITE_LONG 0x8 spl_name
	WRITE_LONG 0x50 spl_desc
END
ACTION_IF FILE_EXISTS_IN_GAME ~spin106.spl~ BEGIN
  COPY_EXISTING ~spin106.spl~ ~override~
	READ_LONG 0x8 spl_name
	READ_LONG 0x50 spl_desc
COPY ~spell_rev\shared\spin106.spl~     ~override~ // Vampiric Drain
	WRITE_LONG 0x8 spl_name
	WRITE_LONG 0x50 spl_desc
END


/* ----Avenger Abilities---- */

COPY ~spell_rev\shared\spdr101.spl~     ~override~ // Chromatic Orb
  SAY NAME1 @433    SAY UNIDENTIFIED_DESC @434
COPY ~spell_rev\shared\spdr201.spl~     ~override~ // Web
  SAY NAME1 @477    SAY UNIDENTIFIED_DESC @478
COPY ~spell_rev\shared\spdr301.spl~     ~override~ // Lightning Bolt
  SAY NAME1 @515    SAY UNIDENTIFIED_DESC @516
COPY ~spell_rev\shared\spdr401.spl~     ~override~ // Improved Invisibility
  SAY NAME1 @569    SAY UNIDENTIFIED_DESC @570
COPY ~spell_rev\shared\spdr501.spl~     ~override~ // Confusion (replaces Chaos)
  SAY NAME1 @561    SAY UNIDENTIFIED_DESC @562
COPY ~spell_rev\shared\spdr601.spl~     ~override~ // Chain Lightning
  SAY NAME1 @687    SAY UNIDENTIFIED_DESC @688


/* ----Beast Master Abilities---- */

COPY ~spell_rev\shared\spra304.spl~     ~override~ // Animal Summoning I
  SAY NAME1 @394    SAY UNIDENTIFIED_DESC @395
COPY ~spell_rev\shared\spra305.spl~     ~override~ // Animal Summoning II
  SAY NAME1 @396    SAY UNIDENTIFIED_DESC @397
COPY ~spell_rev\shared\spra306.spl~     ~override~ // Animal Summoning III
  SAY NAME1 @398    SAY UNIDENTIFIED_DESC @399


/* ----Stalker Abilities---- */

COPY ~spell_rev\shared\spra301.spl~     ~override~ // Haste
  SAY NAME1 @509    SAY UNIDENTIFIED_DESC @510
COPY ~spell_rev\shared\spra302.spl~     ~override~ // Non-Detection
  SAY NAME1 @519    SAY UNIDENTIFIED_DESC @520
COPY ~spell_rev\shared\spra303.spl~     ~override~ // Protection from Missiles
  SAY NAME1 @521    SAY UNIDENTIFIED_DESC @522


/* ----Paladin Abilities---- */

ACTION_IF FILE_EXISTS_IN_GAME ~spcl213.spl~ BEGIN
  COPY_EXISTING ~spcl213.spl~ ~override~
	READ_LONG 0x8 spl_name
	READ_LONG 0x50 spl_desc
COPY ~spell_rev\shared\spcl213.spl~     ~override~ // Protection from Evil
	WRITE_LONG 0x8 spl_name
	WRITE_LONG 0x50 spl_desc
END


/* ----Stormlord Abilities---- */

COPY ~spell_rev\shared\spcl721.spl~     ~override~ // Storm Shield
  SAY NAME1 @1109    SAY UNIDENTIFIED_DESC @1110
COPY ~spell_rev\shared\spcl722.spl~     ~override~ // Lightning Bolt
  SAY NAME1 @515    SAY UNIDENTIFIED_DESC @516


/* ----Innate Abilities---- */

ADD_PROJECTILE ~spell_rev\projectles\dvclfear.pro~
COPY ~spell_rev\shared\fearaura.spl~      ~override~ // Aura of fear
  WRITE_SHORT 0x98 %dvclfear%

COPY ~spell_rev\shared\dvgasfrm.spl~      ~override~ // Gaseous Form
COPY ~spell_rev\shared\dvgasfrm.itm~      ~override~ // Gaseous Form
COPY ~spell_rev\shared\dvtelpor.spl~      ~override~ // Teleport Without Error

ACTION_IF FILE_EXISTS_IN_GAME ~spin113.spl~ BEGIN
  COPY_EXISTING ~spin113.spl~ ~override~
	READ_LONG 0x8 spl_name
	READ_LONG 0x50 spl_desc
COPY ~spell_rev\shared\spin113.spl~      ~override~ // Branwen Spiritual Hammer
	WRITE_LONG 0x8 spl_name
	WRITE_LONG 0x50 spl_desc
END

COPY ~spell_rev\shared\spin683.spl~      ~override~ // Innate Web Tangle
COPY ~spell_rev\shared\spin701.spl~      ~override~ // Death Knight's Unholy Fireball
  SAY NAME1 @872
COPY ~spell_rev\shared\spin701i.eff~      ~override~
COPY ~spell_rev\shared\spin788.spl~      ~override~ // Demilich Soul Trap
COPY ~spell_rev\shared\spin789.spl~      ~override~ // Demilich Howl

//Divine spells.
//Level 1.
//Entangle animations.
COPY ~spell_rev\shared\spentaai.bam~      ~override~  // IWD's Entangle Animation
COPY ~spell_rev\shared\spentaci.bam~      ~override~

//Level 2.
//Flame blade.
//Some of the flame blades are not in use.
COPY ~spell_rev\sppr2##\fblade.itm~     ~override~
COPY ~spell_rev\sppr2##\fblade1.itm~     ~override~
COPY ~spell_rev\sppr2##\fblade2.itm~     ~override~
COPY ~spell_rev\sppr2##\fblade3.itm~     ~override~
COPY ~spell_rev\sppr2##\fblade4.itm~     ~override~
COPY ~spell_rev\sppr2##\fblade5.itm~     ~override~
COPY ~spell_rev\sppr2##\fblade6.itm~     ~override~
COPY ~spell_rev\sppr2##\fblade7.itm~     ~override~
COPY ~spell_rev\sppr2##\fblade8.itm~     ~override~
COPY ~spell_rev\sppr2##\fblade9.itm~     ~override~

//Deprecate old goodberry.
APPEND ~spell.ids~ ~1207 CLERIC_GOOD_BERRIES_DEPRECATED~

// Know Opponent replaces Know Alignment.
APPEND ~spell.ids~ ~1209 CLERIC_KNOW_OPPONENT~

// Resist Elements (replaces Resist Fire and Cold)
APPEND ~spell.ids~ ~1210 CLERIC_RESIST_ELEMENTS~

//Draw upon Holy Might.
//Unused subspell.
COPY ~spell_rev\sppr2##\sppr214w.spl~    ~override~
STRING_SET ~12108~ @57 // change portrait icon name into Draw upon Divine Might

// Cure Moderate Wounds (moved from lvl 3, originally Cure Medium Wounds).
ADD_SPELL ~spell_rev\sppr2##\sppr215.spl~ 1 2 ~CLERIC_CURE_MODERATE_WOUNDS~


//Level 3.
//Dispel magic.
COPY ~spell_rev\sppr3##\sppr303.spl~     ~override~  // Dispel Magic
  SAY NAME1 @75    SAY UNIDENTIFIED_DESC @76

//Old Protection from Fire (disabled)
COPY_EXISTING ~spell.ids~ ~override~
  REPLACE_TEXTUALLY ~^1306[ %TAB%]+CLERIC_PROTECTION_FROM_FIRE\b~ ~1306 CLERIC_PROTECTION_FROM_FIRE_DEPRECATED~

// Break Enchantment (replaces Remove Curse).
APPEND ~spell.ids~ ~1307 CLERIC_BREAK_ENCHANTMENT~

// Cure Serious Wounds (moved from lvl 4, replaces Cure Medium Wounds) 
COPY ~spell_rev\sppr4##\scrl56.itm~     ~override~
  SAY NAME2 @109    SAY IDENTIFIED_DESC   @110

// Gust of Wind (replaces Zone of Sweet Air).
APPEND ~spell.ids~ ~1318 CLERIC_GUST_OF_WIND~

// Summon Insects detectable spells stuff.
LAF ds_altered_spell INT_VAR old_clone=60 new_clone=~-1~ STR_VAR file=~sppr319.spl~ END
APPEND_OUTER ~spell_rev/lib/ds_sr_extra.2da~ ~sppr319a.SPL    233     1     120   146    6     A~


//Level 4.
// Animal Summoning IV (originally Animal Summoning I)
APPEND ~spell.ids~ ~1402 CLERIC_ANIMAL_SUMMONING_LEVEL_4~

COPY ~spell_rev\sppr4##\sppr407.spl~     ~override~  // old Protection from Lightning (disabled)
  SAY NAME1 @123    SAY UNIDENTIFIED_DESC @124
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 7567 parameter1 = RESOLVE_STR_REF(@123) END
COPY ~spell_rev\sppr4##\scrl5c.itm~     ~override~
  SAY NAME2 @123    SAY IDENTIFIED_DESC   @124
COPY_EXISTING ~spell.ids~ ~override~
  REPLACE_TEXTUALLY ~^1407[ %TAB%]+CLERIC_PROTECTION_FROM_LIGHTNING\b~ ~1407 CLERIC_PROTECTION_FROM_LIGHTNING_DEPRECATED~

// change portrait icon name into Divine Power
STRING_SET ~8267~ @133

//Lesser restoration scroll.
COPY ~spell_rev\sppr4##\restore.itm~     ~override~
  SAY NAME2 @143    SAY IDENTIFIED_DESC   @144 


//Level 5.
// old Cure Critical Wounds (disabled) -> Cure Mortal Wounds.
APPEND ~spell.ids~ ~1502 CLERIC_CURE_CRITICAL_WOUNDS_DEPRECATED~

// change portrait icon name into Righteous Fury
STRING_SET ~8272~ @133

// Repulsion (replaces Repulse Undead)
APPEND ~spell.ids~ ~1515 CLERIC_REPULSION~

// Insect Plague detectable spells stuff.
LAF ds_altered_spell INT_VAR old_clone=60 new_clone=~-1~ STR_VAR file=~sppr517.spl~ END
APPEND_OUTER ~spell_rev/lib/ds_sr_extra.2da~ ~sppr517a.SPL    233     2     120   146    6     A~

COPY ~spell_rev\sppr5##\spja01.spl~     ~override~  // Harper's Call
  SAY NAME1 @2157    SAY UNIDENTIFIED_DESC @2158
COPY ~spell_rev\sppr5##\spja01a.eff~     ~override~
COPY ~spell_rev\sppr5##\spja01b.eff~     ~override~
COPY ~spell_rev\sppr5##\spja01c.eff~     ~override~
COPY ~spell_rev\sppr5##\spja01d.eff~     ~override~
COPY ~spell_rev\sppr5##\spja01e.eff~     ~override~
COPY ~spell_rev\sppr5##\spja01f.eff~     ~override~


//Level 6.
// Animal Summoning VI (originally Animal Summoning III)
APPEND ~spell.ids~ ~1602 CLERIC_ANIMAL_SUMMONING_LEVEL_6~

// Blade Barrier (AI's version)
COPY ~spell_rev\sppr6##\sppr698.spl~     ~override~

COPY ~spell_rev\sppr6##\sppr604.spl~     ~override~  // Conjure Animals (disabled)
  SAY NAME1 @197    SAY UNIDENTIFIED_DESC @198
COPY_EXISTING ~spell.ids~ ~override~
APPEND ~spell.ids~ ~1604 CLERIC_CONJURE_ANIMALS_DEPRECATED~

//Patch projectile for fire seeds.
COPY_EXISTING ~bolt2.pro~ ~override~
  WRITE_SHORT 0x204 110
  WRITE_SHORT 0x206 110

//False Dawn: unused effs.
COPY ~spell_rev\sppr6##\dawnvis2.eff~     ~override~
COPY ~spell_rev\sppr6##\dawndam2.eff~     ~override~
COPY ~spell_rev\sppr6##\dawnblnd.eff~     ~override~

//Detectable spells stuff for physical mirror.
LAF ds_altered_spell INT_VAR old_clone=197 new_clone=~142~ STR_VAR file=~sppr613.spl~ END

//Override projectile for sol's searing orb.
COPY ~spell_rev\projectles\bulletex.pro~     ~override~

//ADD_SPELL: Conjure Air Elemental
ADD_SPELL ~spell_rev\sppr6##\sppr621.spl~ 1 6 ~CLERIC_CONJURE_AIR_ELEMENTAL~  // Conjure Air Elemental (added to druid's spells)

//ADD_SPELL: Conjure Earth Elemental
ADD_SPELL ~spell_rev\sppr6##\sppr622.spl~ 1 6 ~CLERIC_CONJURE_EARTH_ELEMENTAL~  // Conjure Earth Elemental (moved from lvl 7)


//Level 7.
// SPPR702 is "Stalker" in IWDEE, a spell that summons Shambling Mounds
APPEND ~spell.ids~ ~1702 CLERIC_STALKER~
  UNLESS ~^1702[ %TAB%]+CLERIC_STALKER\b~

// Summon Death Knight (replaces Gate)
APPEND ~spell.ids~ ~1703 CLERIC_SUMMON_DEATH_KNIGHT~

//Resources for Symbol of weakness but they do not seem to be used anywhere.
//Maybe they are resources for the projectile but no reference changes seem to be made.
COPY ~spell_rev\sppr7##\a#spain.bam~     ~override~
COPY ~spell_rev\sppr7##\a#ispain.vvc~     ~override~
// Symbol of Weakness (replaces Symbol, Fear)
APPEND ~spell.ids~ ~1706 CLERIC_SYMBOL_WEAKNESS~

// Chaos (replaces Confusion)
APPEND ~spell.ids~ ~1709 CLERIC_CHAOS~

//Effect for holy word but does not seem to be used anywhere.
COPY ~spell_rev\sppr7##\dvhoword.eff~     ~override~

//Effect for unholy word but does not seem to be used anywhere.
COPY ~spell_rev\sppr7##\dvunword.eff~     ~override~

COPY ~spell_rev\sppr7##\sppr717.spl~     ~override~  // Creeping Doom
  SAY NAME1 @257    SAY UNIDENTIFIED_DESC @258
COPY ~spell_rev\sppr7##\sppr717a.spl~     ~override~
COPY ~spell_rev\sppr7##\sppr717b.spl~     ~override~
LAF ds_altered_spell INT_VAR old_clone=60 new_clone=~-1~ STR_VAR file=~sppr717.spl~ END
APPEND_OUTER ~spell_rev/lib/ds_sr_extra.2da~ ~sppr717a.SPL    233     3     120   146    6     A~

//Resources for Symbol of stunning but they do not seem to be used anywhere.
//Maybe they are resources for the projectile but no reference changes seem to be made.
COPY ~spell_rev\sppr7##\a#shope.bam~     ~override~
COPY ~spell_rev\sppr7##\a#ishope.vvc~     ~override~ 

//Earthquake.
//Resource not used anywhere by the mod, but present in the folder.
//COPY ~spell_rev\sppr7##\sppr720f.spl~     ~override~

//Animal Summoning VII: surgery on spell.ids
APPEND ~spell.ids~ ~%CLERIC_ANIMAL_SUMMONING_4% CLERIC_ANIMAL_SUMMONING_LEVEL_7~


/*-----------------------level 8-----------------------*/

COPY ~spell_rev\sppr7##\sppr721.spl~     ~override~  // Energy Blades
  SAY NAME1 @271    SAY UNIDENTIFIED_DESC @272

COPY ~spell_rev\sppr7##\sppr722.spl~     ~override~  // Storm of Vengeance
  SAY NAME1 @273    SAY UNIDENTIFIED_DESC @274

COPY ~spell_rev\sppr7##\sppr723.spl~     ~override~  // Elemental Swarm
  SAY NAME1 @275    SAY UNIDENTIFIED_DESC @276

COPY ~spell_rev\sppr7##\sppr724.spl~     ~override~  // Elemental Prince Call
  SAY NAME1 @277    SAY UNIDENTIFIED_DESC @278
COPY ~spell_rev\sppr7##\elemchan.bcs~     ~override~
COPY ~spell_rev\sppr7##\elemchan.cre~     ~override~
  SAY NAME1 @2277
  SAY NAME2 @2277
COPY ~spell_rev\sppr7##\sumchan.eff~     ~override~
COPY ~spell_rev\sppr7##\elemchan.itm~     ~override~
COPY ~spell_rev\sppr7##\elemsunn.bcs~     ~override~
COPY ~spell_rev\sppr7##\elemsunn.cre~     ~override~
  SAY NAME1 @2278
  SAY NAME2 @2278
COPY ~spell_rev\sppr7##\sumsunn.eff~     ~override~
COPY ~spell_rev\sppr7##\elemsunn.itm~     ~override~
COPY ~spell_rev\sppr7##\dvsunnis.spl~     ~override~
COPY ~spell_rev\sppr7##\elemzaam.bcs~     ~override~
COPY ~spell_rev\sppr7##\elemzaam.cre~     ~override~
  SAY NAME1 @2279
  SAY NAME2 @2279
COPY ~spell_rev\sppr7##\sumzaam.eff~     ~override~
COPY ~spell_rev\sppr7##\elemzaam.itm~     ~override~
COPY ~spell_rev\sppr7##\dvzaaman.spl~     ~override~

COPY ~spell_rev\sppr7##\sppr725.spl~     ~override~  // Globe of Blades
  SAY NAME1 @279    SAY UNIDENTIFIED_DESC @280
COPY ~spell_rev\sppr7##\sppr725d.spl~     ~override~
COPY ~spell_rev\sppr7##\sppr725e.spl~     ~override~

COPY ~spell_rev\sppr7##\sppr726.spl~     ~override~  // Summon Deva
  SAY NAME1 @281    SAY UNIDENTIFIED_DESC @282
COPY ~spell_rev\sppr7##\devagood.cre~     ~override~
  SAY NAME1 @2281
  SAY NAME2 @2281
COPY ~spell_rev\sppr7##\dvdevag.bcs~     ~override~
COPY ~spell_rev\sppr7##\dvdevaga.itm~     ~override~
COPY ~spell_rev\sppr7##\dvdevagr.itm~     ~override~
COPY ~spell_rev\sppr7##\dvdevagw.itm~     ~override~

COPY ~spell_rev\sppr7##\dw#devag.spl~     ~override~  // SCSII Summon Deva

COPY ~spell_rev\sppr7##\sppr727.spl~     ~override~  // Summon Fallen Deva
  SAY NAME1 @283    SAY UNIDENTIFIED_DESC @284
COPY ~spell_rev\sppr7##\devaevil.cre~     ~override~
  SAY NAME1 @2283
  SAY NAME2 @2283
COPY ~spell_rev\sppr7##\dvdevae.bcs~     ~override~
COPY ~spell_rev\sppr7##\dvdevaea.itm~     ~override~
COPY ~spell_rev\sppr7##\dvdevaer.itm~     ~override~
COPY ~spell_rev\sppr7##\dvdevaew.itm~     ~override~

COPY ~spell_rev\sppr7##\dw#devae.spl~     ~override~  // SCSII Summon Fallen Deva

COPY ~spell_rev\sppr7##\sppr728.spl~     ~override~  // Implosion
  SAY NAME1 @285    SAY UNIDENTIFIED_DESC @286
COPY ~spell_rev\sppr7##\dvimplo.bam~     ~override~
COPY ~spell_rev\sppr7##\dvimplo.eff~     ~override~
COPY ~spell_rev\sppr7##\dvimplo.vvc~     ~override~

COPY ~spell_rev\sppr7##\sppr729.spl~     ~override~  // Mass Raise Dead
  SAY NAME1 @287    SAY UNIDENTIFIED_DESC @288

COPY ~spell_rev\sppr7##\sppr730.spl~     ~override~  // Aura of Flaming Death
  SAY NAME1 @289    SAY UNIDENTIFIED_DESC @290
COPY ~spell_rev\sppr7##\sppr730d.spl~     ~override~
COPY ~spell_rev\sppr7##\dvflmhit.eff~     ~override~

COPY ~spell_rev\sppr7##\sppr731.spl~     ~override~  // Fire Elemental Transformation
  SAY NAME1 @291    SAY UNIDENTIFIED_DESC @292
COPY ~spell_rev\sppr7##\sppr731.itm~     ~override~

COPY ~spell_rev\sppr7##\sppr732.spl~     ~override~  // Earth Elemental Transformation
  SAY NAME1 @293    SAY UNIDENTIFIED_DESC @294
COPY ~spell_rev\sppr7##\sppr732.itm~     ~override~


//Arcane spells.
//Level 1.
// Grease projectile.
COPY_EXISTING ~grease.pro~ ~override~
  WRITE_SHORT 0x206 110

// Obscuring Mist (replaces Blindness).
APPEND ~spell.ids~ ~2106 WIZARD_OBSCURING_MIST~

// Monster Summoning I (replaces Friends)
APPEND ~spell.ids~ ~2107 WIZARD_MONSTER_SUMMONING_LEVEL_1~

// True Strike (replaces Infravision)
APPEND ~spell.ids~ ~2111 WIZARD_TRUE_STRIKE~

//Chromatic orb: subspell for what??
COPY ~spell_rev\spwi1##\spwi118z.spl~     ~override~
// Chromatic orb projectile.
COPY ~spell_rev\spwi1##\spchrorb.bam~     ~override~
COPY ~spell_rev\spwi1##\chromorb.pro~     ~override~

// Find Familiar
COPY ~spell_rev\spwi1##\spwi123.spl~     ~override~
  SAY NAME1 @439    SAY UNIDENTIFIED_DESC @440
COPY ~spell_rev\spwi1##\scrl6d.itm~     ~override~
  SAY NAME2 @439    SAY IDENTIFIED_DESC   @440
COPY ~spell_rev\spwi1##\famcat.cre~     ~override~
  SAY NAME1 @1042
  SAY NAME2 @1042
COPY ~spell_rev\spwi1##\famcat.itm~     ~override~
  SAY NAME1 @1025
  SAY NAME2 @1025
  SAY UNIDENTIFIED_DESC @1008
COPY ~spell_rev\spwi1##\famcat25.cre~     ~override~
  SAY NAME1 @1042
  SAY NAME2 @1042
COPY ~spell_rev\spwi1##\famcat25.itm~     ~override~
  SAY NAME1 @1025
  SAY NAME2 @1025
  SAY UNIDENTIFIED_DESC @1009
COPY ~spell_rev\spwi1##\famdust.cre~     ~override~
  SAY NAME1 @1043
  SAY NAME2 @1043
COPY ~spell_rev\spwi1##\famdust.itm~     ~override~
  SAY NAME1 @1025
  SAY NAME2 @1025
  SAY UNIDENTIFIED_DESC @1010
COPY ~spell_rev\spwi1##\famdus25.cre~     ~override~
  SAY NAME1 @1043
  SAY NAME2 @1043
COPY ~spell_rev\spwi1##\famdus25.itm~     ~override~
  SAY NAME1 @1025
  SAY NAME2 @1025
  SAY UNIDENTIFIED_DESC @1011
COPY ~spell_rev\spwi1##\famfair.cre~     ~override~
  SAY NAME1 @1044
  SAY NAME2 @1044
COPY ~spell_rev\spwi1##\famfair.itm~     ~override~
  SAY NAME1 @1025
  SAY NAME2 @1025
  SAY UNIDENTIFIED_DESC @1012
COPY ~spell_rev\spwi1##\famfai25.cre~     ~override~
  SAY NAME1 @1044
  SAY NAME2 @1044
COPY ~spell_rev\spwi1##\famfai25.itm~     ~override~
  SAY NAME1 @1025
  SAY NAME2 @1025
  SAY UNIDENTIFIED_DESC @1013
COPY ~spell_rev\spwi1##\famfer.cre~     ~override~
  SAY NAME1 @1045
  SAY NAME2 @1045
COPY ~spell_rev\spwi1##\famfer.itm~     ~override~
  SAY NAME1 @1025
  SAY NAME2 @1025
  SAY UNIDENTIFIED_DESC @1014
COPY ~spell_rev\spwi1##\famfer25.cre~     ~override~
  SAY NAME1 @1045
  SAY NAME2 @1045
COPY ~spell_rev\spwi1##\famfer25.itm~     ~override~
  SAY NAME1 @1025
  SAY NAME2 @1025
  SAY UNIDENTIFIED_DESC @1015
COPY ~spell_rev\spwi1##\famimp.cre~     ~override~
  SAY NAME1 @1046
  SAY NAME2 @1046
COPY ~spell_rev\spwi1##\famimp.itm~     ~override~
  SAY NAME1 @1025
  SAY NAME2 @1025
  SAY UNIDENTIFIED_DESC @1016
COPY ~spell_rev\spwi1##\famimp25.cre~     ~override~
  SAY NAME1 @1046
  SAY NAME2 @1046
COPY ~spell_rev\spwi1##\famimp25.itm~     ~override~
  SAY NAME1 @1025
  SAY NAME2 @1025
  SAY UNIDENTIFIED_DESC @1017
COPY ~spell_rev\spwi1##\fampsd.cre~     ~override~
  SAY NAME1 @1047
  SAY NAME2 @1047
COPY ~spell_rev\spwi1##\fampsd.itm~     ~override~
  SAY NAME1 @1025
  SAY NAME2 @1025
  SAY UNIDENTIFIED_DESC @1018
COPY ~spell_rev\spwi1##\fampsd25.cre~     ~override~
  SAY NAME1 @1047
  SAY NAME2 @1047
COPY ~spell_rev\spwi1##\fampsd25.itm~     ~override~
  SAY NAME1 @1025
  SAY NAME2 @1025
  SAY UNIDENTIFIED_DESC @1019
COPY ~spell_rev\spwi1##\famquas.cre~     ~override~
  SAY NAME1 @1048
  SAY NAME2 @1048
COPY ~spell_rev\spwi1##\famquas.itm~     ~override~
  SAY NAME1 @1025
  SAY NAME2 @1025
  SAY UNIDENTIFIED_DESC @1020
COPY ~spell_rev\spwi1##\famqua25.cre~     ~override~
  SAY NAME1 @1048
  SAY NAME2 @1048
COPY ~spell_rev\spwi1##\famqua25.itm~     ~override~
  SAY NAME1 @1025
  SAY NAME2 @1025
  SAY UNIDENTIFIED_DESC @1021
COPY ~spell_rev\spwi1##\famrab.cre~     ~override~
  SAY NAME1 @1049
  SAY NAME2 @1049
COPY ~spell_rev\spwi1##\famrab.itm~     ~override~
  SAY NAME1 @1025
  SAY NAME2 @1025
  SAY UNIDENTIFIED_DESC @1022
COPY ~spell_rev\spwi1##\famrab25.cre~     ~override~
  SAY NAME1 @1049
  SAY NAME2 @1049
COPY ~spell_rev\spwi1##\famrab25.itm~     ~override~
  SAY NAME1 @1025
  SAY NAME2 @1025
  SAY UNIDENTIFIED_DESC @1023
COPY ~spell_rev\spwi1##\impclaw.itm~     ~override~
COPY ~spell_rev\spwi1##\mepfir.itm~     ~override~
COPY ~spell_rev\spwi1##\psdclaw.itm~     ~override~
COPY ~spell_rev\spwi1##\quasclaw.itm~     ~override~

// Detect Alignment (moved from lvl 2)
ADD_SPELL ~spell_rev\spwi1##\spwi126.spl~ 2 1 ~WIZARD_KNOW_ALIGNMENT~
  //New desc ref because old version still around -- see below.
  SAY NAME1 @453    SAY UNIDENTIFIED_DESC @2000
// TODO: add scroll


//Level 2.
// old Detect Alignment (disabled, originally Detect Evil)
APPEND ~spell.ids~ ~2202 WIZARD_DETECT_EVIL_DEPRECATED~

// Battering Ram ("replaces" Knock)
APPEND ~spell.ids~ ~2207 WIZARD_BATTERING_RAM~

// Know Opponent (replaces Know Alignment)
APPEND ~spell.ids~ ~2208 WIZARD_KNOW_OPPONENT~

// Web projectile
COPY_EXISTING ~web.pro~ ~override~
  WRITE_SHORT 0x206 190

// Sound Burst (replaces Deafness).
APPEND ~spell.ids~ ~2223 WIZARD_SOUND_BURST~

// scroll bam for Resist elements.
COPY ~spell_rev\spwi2##\dvpr210a.bam~   ~override~  
COPY ~spell_rev\spwi2##\scrl86.itm~     ~override~  // vanilla's Detect Evil scroll
  SAY NAME2 @864    SAY IDENTIFIED_DESC   @865

//Level 3.
COPY ~spell_rev\spwi3##\spwi302.spl~     ~override~  // Remove Magic
  SAY NAME1 @503    SAY UNIDENTIFIED_DESC @504

ACTION_IF (GAME_INCLUDES ~bg2~) BEGIN
  COPY_EXISTING ~cut01b.bcs~ ~override~
    DECOMPILE_AND_PATCH BEGIN
      REPLACE_TEXTUALLY ~WIZARD_FLAME_ARROW~ ~WIZARD_MELF_ACID_ARROW~
    END
    BUT_ONLY
END

// Monster Summoning III (originally Monster Summoning I)
APPEND ~spell.ids~ ~2309 WIZARD_MONSTER_SUMMONING_LEVEL_3~

//Non-detection: detectable spells stuff.
APPEND_OUTER ~spell_rev/lib/ds_sr_extra.2da~ ~spwi310.SPL    282     3     6     142    n     A~

COPY ~spell_rev\spwi3##\spwi320.spl~     ~override~  // Protection from Cold
  SAY NAME1 @537    SAY UNIDENTIFIED_DESC @538
/* COPY ~spell_rev\spwi3##\scrl6i.itm~     ~override~
  SAY NAME2 @537    SAY IDENTIFIED_DESC   @538 */  // Scroll used for Icelance
  
//Patching for hold undead projectile.
COPY_EXISTING ~holdnecr.pro~ ~override~
  WRITE_SHORT 0x204 65
  WRITE_SHORT 0x206 65

COPY ~spell_rev\spwi3##\spwi326.spl~     ~override~  // Dispel Magic
  SAY NAME1 @547    SAY UNIDENTIFIED_DESC @548

//Level 4.
// Dimension Door (disabled)
APPEND ~spell.ids~ ~2402 WIZARD_DIMENSION_DOOR_DEPRECATED~

COPY ~spell_rev\spwi4##\spwi403.spl~     ~override~  // Fire Shield (Blue) (AI only now)
  SAY NAME1 @565    SAY UNIDENTIFIED_DESC @566
/* COPY ~spell_rev\spwi4##\scrl1w.itm~     ~override~  // Scroll used for Mestil's Acid Sheath
  SAY NAME2 @565    SAY IDENTIFIED_DESC   @566
COPY ~spell_rev\spwi4##\spwi403a.spl~     ~override~
COPY ~spell_rev\spwi4##\spwi403b.spl~     ~override~
COPY ~spell_rev\spwi4##\spwi403c.spl~     ~override~
COPY ~spell_rev\spwi4##\spwi403d.spl~     ~override~
COPY ~spell_rev\spwi4##\spwi403e.spl~     ~override~
COPY ~spell_rev\spwi4##\spwi403f.spl~     ~override~
COPY ~spell_rev\spwi4##\spwi403g.spl~     ~override~
COPY ~spell_rev\spwi4##\spwi403h.spl~     ~override~ */

// Ice Storm projectile.
COPY_EXISTING ~icestorm.pro~ ~override~
  WRITE_BYTE 0x216 4

// old Monster Summoning IV (disabled)
COPY ~spell_rev\spwi4##\spwi407.spl~     ~override~
  SAY NAME1 @573    SAY UNIDENTIFIED_DESC @574
COPY ~spell_rev\spwi4##\gnollsu.eff~     ~override~
COPY ~spell_rev\spwi4##\gnollsu.cre~     ~override~
COPY ~spell_rev\spwi4##\gnollsu.itm~     ~override~
COPY ~spell_rev\spwi4##\gnlcapsu.eff~     ~override~
COPY ~spell_rev\spwi4##\gnlcapsu.cre~     ~override~
  SAY NAME1 #19691
  SAY NAME2 #19691
COPY ~spell_rev\spwi4##\gnlcapsu.itm~     ~override~
COPY_EXISTING ~spell.ids~ ~override~
  REPLACE_TEXTUALLY ~^2407[ %TAB%]+WIZARD_MONSTER_SUMMONING_2\b~ ~2407 WIZARD_MONSTER_SUMMONING_2_DEPRECATED~

// Break Enchantment (replaces Remove Curse)
APPEND ~spell.ids~ ~2410 WIZARD_BREAK_ENCHANTMENT~

COPY ~spell_rev\spwi4##\spwi413.spl~     ~override~  // Otiluke's Resilient Sphere
  SAY NAME1 @585    SAY UNIDENTIFIED_DESC @586
COPY ~spell_rev\spwi4##\spwi413c.spl~     ~override~
COPY ~spell_rev\spwi4##\spwi413d.spl~     ~override~
COPY ~spell_rev\spwi4##\spwi413c.eff~     ~override~
COPY ~spell_rev\spwi4##\spwi413d.eff~     ~override~

//These do not seem to be used anywhere in Polymorph other.
COPY ~spell_rev\spwi4##\plysquir.eff~     ~override~
COPY ~spell_rev\spwi4##\squirp.itm~     ~override~

COPY ~spell_rev\spwi4##\spwi416.spl~     ~override~  // Polymorph Self
  SAY NAME1 @591    SAY UNIDENTIFIED_DESC @592
COPY ~spell_rev\spwi4##\scrl5m.itm~     ~override~
  SAY NAME2 @591    SAY IDENTIFIED_DESC   @592
COPY ~spell_rev\spwi4##\spwi461.itm~     ~override~
COPY ~spell_rev\spwi4##\spwi461.spl~     ~override~
COPY ~spell_rev\spwi4##\spwi462.itm~     ~override~
COPY ~spell_rev\spwi4##\spwi462.spl~     ~override~
COPY ~spell_rev\spwi4##\spwi463.itm~     ~override~
COPY ~spell_rev\spwi4##\spwi463.spl~     ~override~
COPY ~spell_rev\spwi4##\spwi464.itm~     ~override~
COPY ~spell_rev\spwi4##\spwi464.spl~     ~override~
COPY ~spell_rev\spwi4##\spwi465.itm~     ~override~
COPY ~spell_rev\spwi4##\spwi465.spl~     ~override~
  SAY NAME1 ~Shapeshifts Winter Wolf~

//Seemingly unused phase spider.
COPY ~spell_rev\spwi4##\spidphsu.cre~     ~override~
COPY ~spell_rev\spwi4##\spidphsu.itm~     ~override~
// Monster Summoning IV ("replaces" Spider Spawn)
APPEND ~spell.ids~ ~2423 WIZARD_MONSTER_SUMMONING_2~
APPEND ~spell.ids~ ~2423 WIZARD_MONSTER_SUMMONING_LEVEL_4~

//Level 5.
// Summon Shadow (replaces Animate Dead)
APPEND ~spell.ids~ ~2501 WIZARD_SUMMON_SHADOW~

//Why is this being copied for cone of cold?
COPY_EXISTING ~spccoldl.bam~ ~override~

// Monster Summoning V (originally Monster Summoning III)
APPEND ~spell.ids~ ~2504 WIZARD_MONSTER_SUMMONING_LEVEL_5~

//Waves of Fatigue (replaces Chaos)
COPY_EXISTING ~spell.ids~ ~override~
  REPLACE_TEXTUALLY ~^2508[ %TAB%]+WIZARD_CHAOS~ ~2508 WIZARD_WAVES_OF_FATIGUE~

//Detectable spells stuff for Dispelling screen.
LAF ds_altered_spell INT_VAR old_clone=142 new_clone=~-1~ STR_VAR file=~spwi590.spl~ END
// Dispelling Screen (replaces Spell Immunity)
APPEND ~spell.ids~ ~2510 WIZARD_DISPELLING_SCREEN~

COPY ~spell_rev\spwi5##\spwi590.spl~     ~override~ // SI:Abj replaced by Dispelling Screen
  SAY NAME1 @629    SAY UNIDENTIFIED_DESC @630
LAF ds_altered_spell INT_VAR old_clone=142 new_clone=~-1~ STR_VAR file=~spwi590.spl~ END
COPY ~spell_rev\spwi5##\spwi591.spl~     ~override~
COPY ~spell_rev\spwi5##\spwi592.spl~     ~override~ // SI:Div replaced by Non-detection
  SAY NAME1 @519    SAY UNIDENTIFIED_DESC @520
COPY ~spell_rev\spwi5##\spwi593.spl~     ~override~ // SI:Ench replaced by Mind Blank
  SAY NAME1 @769    SAY UNIDENTIFIED_DESC @770
COPY ~spell_rev\spwi5##\spwi594.spl~     ~override~
COPY ~spell_rev\spwi5##\spwi595.spl~     ~override~
COPY ~spell_rev\spwi5##\spwi596.spl~     ~override~
COPY ~spell_rev\spwi5##\spwi597.spl~     ~override~

//Detectable spells stuff for spell deflection.
LAF ds_altered_spell INT_VAR old_clone=200 new_clone=~-1~ STR_VAR file=~spwi522.spl~ END
APPEND_OUTER ~spell_rev/lib/ds_sr_extra.2da~ ~SPWI522.SPL    233     1     116   201    n     A~
APPEND ~spell.ids~ ~2522 WIZARD_SPELL_DEFLECTION~

/*
ADD_SPELL ~spell_rev\spwi5##\spwi524.spl~ 2 5 ~WIZARD_BALL_LIGHTNING~  // Ball Lightning (new spell)
  SAY NAME1 @565    SAY UNIDENTIFIED_DESC @566
COPY ~spell_rev\spwi5##\scrl1w.itm~     ~override~
  SAY NAME2 @565    SAY IDENTIFIED_DESC   @566
COPY ~spell_rev\spwi5##\mestsh.vvc~     ~override~
COPY ~spell_rev\spwi5##\mestsh.bam~     ~override~
*/

//Seemingly not needed.
COPY ~spell_rev\spwi5##\fireelem.itm~     ~override~

//ADD_SPELL: Mestil's Acid Sheath
ADD_SPELL ~spell_rev\spwi5##\spwi526.spl~ 2 5 ~WIZARD_MESTILS_ACID_SHEATH~  // Mestil's Acid Sheath (new spell)
  SAY NAME1 @565    SAY UNIDENTIFIED_DESC @566
COPY ~spell_rev\spwi5##\scrl1w.itm~      ~override~
  SAY NAME2 @565    SAY IDENTIFIED_DESC   @566
COPY ~spell_rev\spwi5##\dvwi526d.spl~    ~override~
COPY ~spell_rev\spwi5##\mestsh.vvc~      ~override~
COPY ~spell_rev\spwi5##\mestsh.bam~      ~override~
COPY ~spell_rev\spwi5##\dvwi526a.bam~    ~override~
COPY ~spell_rev\spwi5##\dvwi526b.bam~    ~override~
COPY ~spell_rev\spwi5##\dvwi526c.bam~    ~override~
/* STRING_SET ~13070~ @565 // change portrait icon from Fire Shield (Blue) to Acid Sheath */


//Level 6.
//Invisible stalker: what is this cre for? Overriding vanilla?
COPY ~spell_rev\spwi6##\stalke.cre~     ~override~

//Replace Death spell with banishment.
APPEND ~spell.ids~ ~2605 WIZARD_BANISHMENT~

//Mislead: what are these resources for?
COPY ~spell_rev\spwi6##\mislead.spl~     ~override~
COPY ~spell_rev\spwi6##\dvnosong.spl~     ~override~

//Acid Fog replaces Death Fog spell.
APPEND ~spell.ids~ ~2614 WIZARD_ACID_FOG~

//Overwrite disintegrate projectile.
//Currently a *new* pro is added.
COPY ~spell_rev\spwi6##\spgreorb.pro~     ~override~

//Old Spell Deflection (disabled)
COPY ~spell_rev\spwi6##\spwi618.spl~     ~override~
  SAY NAME1 @693    SAY UNIDENTIFIED_DESC @694
/* COPY ~spell_rev\spwi6##\scrl7v.itm~     ~override~
  SAY NAME2 @721    SAY IDENTIFIED_DESC   @722 */
COPY_EXISTING ~spell.ids~ ~override~
  REPLACE_TEXTUALLY ~^2618[ %TAB%]+WIZARD_SPELL_DEFLECTION\b~ ~2618 WIZARD_SPELL_DEFLECTION_DEPRECATED~

// Animate Skeleton Warrior (replaces Summon Carrion)
APPEND ~spell.ids~ ~2623 WIZARD_ANIMATE_SKELETON_WARRIOR~

/* COPY ~spell_rev\spwi6##\ghastsu.eff~     ~override~
COPY ~spell_rev\spwi6##\ghastsu.cre~     ~override~
COPY ~spell_rev\spwi6##\ghastsu.itm~     ~override~
OUTER_SET dvstench = IDS_OF_SYMBOL (~projectl~ ~dvstench~) + 1
ACTION_IF (dvstench < 1) BEGIN
  ADD_PROJECTILE ~spell_rev\projectles\dvstench.pro~
END
COPY ~spell_rev\spwi6##\dvstench.spl~     ~override~
  WRITE_SHORT 0x98 %dvstench%
COPY ~spell_rev\spwi6##\dvstench.eff~     ~override~
COPY ~spell_rev\spwi6##\mummysu.eff~     ~override~
COPY ~spell_rev\spwi6##\mummysu.cre~     ~override~
COPY ~spell_rev\spwi6##\mummysu.itm~     ~override~
COPY ~spell_rev\spwi6##\mummysu.bcs~     ~override~
COPY ~spell_rev\spwi6##\mummydsp.spl~     ~override~
COPY ~spell_rev\spwi6##\mummydsp.eff~     ~override~ */

// Summon Nishruu: no scroll? the following is commented out.
/* COPY ~spell_rev\spwi6##\scrl8b.itm~     ~override~
  SAY NAME2 @705    SAY IDENTIFIED_DESC   @706 */

COPY ~spell_rev\spwi6##\spwi625.spl~     ~override~  // Stone to Flesh
  SAY NAME1 @707    SAY UNIDENTIFIED_DESC @708
/* COPY ~spell_rev\spwi6##\scrl8c.itm~     ~override~
  SAY NAME2 @707    SAY IDENTIFIED_DESC   @708 */

//COPY ~spell_rev\spwi6##\spin686.spl~     ~override~
/* COPY ~spell_rev\spwi6##\wand18.itm~     ~override~ */

//Monster Summoning VI: replaces Wyvern Call and goes into Monster Summon IV slot.
APPEND ~spell.ids~ ~%WIZARD_MONSTER_SUMMONING_4% WIZARD_MONSTER_SUMMONING_LEVEL_6~


//Level 7.
// Greater Spell Deflection (replaces Spell Turning)
APPEND ~spell.ids~ ~2701 WIZARD_GREATER_SPELL_DEFLECTION~
//Detectable spells stuff.
LAF ds_altered_spell INT_VAR old_clone=200 new_clone=~-1~ STR_VAR file=~spwi701.spl~ END
APPEND_OUTER ~spell_rev/lib/ds_sr_extra.2da~ ~spwi701.SPL    233     2     116   201    n     A~

//Project image.
//Seemingly unused resource.
COPY ~spell_rev\spwi7##\PROJIMAG.SPL~     ~override~

// Summon Death Knight (replaces Cacofiend)
APPEND ~spell.ids~ ~2707 WIZARD_SUMMON_DEATH_KNIGHT~

//Chaos ("replaces" Sphere of Chaos)
APPEND ~spell.ids~ ~2711 WIZARD_CHAOS~

//Seemingly unused effect for finger of death.
COPY ~spell_rev\spwi7##\dvfingwi.eff~     ~override~

COPY ~spell_rev\spwi7##\spwi718.spl~     ~override~  // Summon Djinni
  SAY NAME1 @751    SAY UNIDENTIFIED_DESC @752
COPY ~spell_rev\spwi7##\dvdjinni.eff~     ~override~
COPY ~spell_rev\spwi7##\dvdjinni.cre~     ~override~
  SAY NAME1 @3751
  SAY NAME2 @3751
COPY ~spell_rev\spwi7##\dvdjinni.itm~     ~override~

COPY ~spell_rev\spwi7##\spwi719.spl~     ~override~  // Summon Nishruu/Hakeashar
  SAY NAME1 @705    SAY UNIDENTIFIED_DESC @706
COPY ~spell_rev\spwi7##\nishrusu.cre~     ~override~
  SAY NAME1 @3705
  SAY NAME2 @3705
COPY ~spell_rev\spwi7##\nishruu.itm~     ~override~
COPY ~spell_rev\spwi7##\nishru01.bcs~     ~override~
COPY ~spell_rev\spwi7##\haksu.cre~     ~override~
  SAY NAME1 @3753
  SAY NAME2 @3753
COPY ~spell_rev\spwi7##\haksu.itm~     ~override~

// Mass Heal (limited wish)
// the other resources (summoning eff, djinni, etc. are not overriden).
COPY ~spell_rev\spwi7##\spin734.spl~     ~override~

//ADD_SPELL: Monster Summoning VII
ADD_SPELL ~spell_rev\spwi7##\spwi724.spl~ 2 7 ~WIZARD_MONSTER_SUMMONING_5~  // Monster Summoning VII (added by V4)
APPEND ~spell.ids~ ~%WIZARD_MONSTER_SUMMONING_5% WIZARD_MONSTER_SUMMONING_LEVEL_7~
// vanilla's Summon Nishruu scroll
COPY ~spell_rev\spwi7##\scrl8b.itm~     ~override~


/*-----------------------level 8-----------------------*/

COPY ~spell_rev\spwi8##\spwi801.spl~     ~override~  // Ghostform (new alteration spell)
  SAY NAME1 @767    SAY UNIDENTIFIED_DESC @768
COPY ~spell_rev\spwi8##\scrlw801.itm~     ~override~
  SAY NAME2 @767    SAY IDENTIFIED_DESC   @768
APPEND ~spell.ids~ ~2801 WIZARD_GHOSTFORM~

COPY ~spell_rev\spwi8##\spwi802.spl~     ~override~  // Mind Blank (new spell)
  SAY NAME1 @769    SAY UNIDENTIFIED_DESC @770
COPY ~spell_rev\spwi8##\scrl8d.itm~     ~override~
  SAY NAME2 @769    SAY IDENTIFIED_DESC   @770
COPY ~spell_rev\spwi8##\spwi802a.bam~    ~override~
COPY ~spell_rev\spwi8##\spwi802b.bam~    ~override~
COPY ~spell_rev\spwi8##\spwi802c.bam~    ~override~
APPEND ~spell.ids~ ~2802 WIZARD_MIND_BLANK~
  UNLESS ~^2802[ %TAB%]+WIZARD_MIND_BLANK\b~ // this spell already exists in IWDEE

COPY ~spell_rev\spwi8##\spwi803.spl~     ~override~  // Protection from Energy
  SAY NAME1 @771    SAY UNIDENTIFIED_DESC @772
COPY ~spell_rev\spwi8##\scrl8y.itm~     ~override~
  SAY NAME2 @771    SAY IDENTIFIED_DESC   @772

COPY ~spell_rev\spwi8##\spwi804.spl~     ~override~  // Simulacrum
  SAY NAME1 @773    SAY UNIDENTIFIED_DESC @774
COPY ~spell_rev\spwi8##\scrl8z.itm~     ~override~
  SAY NAME2 @773    SAY IDENTIFIED_DESC   @774
COPY ~spell_rev\spwi8##\SIMULACR.SPL~     ~override~

COPY ~spell_rev\spwi8##\spwi805.spl~     ~override~  // Pierce Shield
  SAY NAME1 @775    SAY UNIDENTIFIED_DESC @776
COPY ~spell_rev\spwi8##\scrl9a.itm~     ~override~
  SAY NAME2 @775    SAY IDENTIFIED_DESC   @776

COPY ~spell_rev\spwi8##\spwi807.spl~     ~override~  // Summon Fiend
  SAY NAME1 @777    SAY UNIDENTIFIED_DESC @778
COPY ~spell_rev\spwi8##\scrl9b.itm~     ~override~
  SAY NAME2 @777    SAY IDENTIFIED_DESC   @778
COPY ~spell_rev\spwi8##\spfiend.eff~      ~override~
COPY ~spell_rev\spwi8##\demglasu.cre~     ~override~
  SAY NAME1 @3777
  SAY NAME2 @3777
COPY ~spell_rev\spwi8##\dvglabre.bcs~     ~override~
COPY ~spell_rev\spwi8##\demglasu.itm~     ~override~

COPY ~spell_rev\spwi8##\spwi808.spl~     ~override~  // Moment of Prescience (replaces Improved Mantle)
  SAY NAME1 @779    SAY UNIDENTIFIED_DESC @780
COPY ~spell_rev\spwi8##\scrl9c.itm~     ~override~
  SAY NAME2 @779    SAY IDENTIFIED_DESC   @780
COPY ~spell_rev\spwi8##\dvwi808a.bam~     ~override~
COPY ~spell_rev\spwi8##\dvwi808b.bam~     ~override~
COPY ~spell_rev\spwi8##\dvwi808c.bam~     ~override~
APPEND ~spell.ids~ ~2808 WIZARD_MOMENT_OF_PRESCIENCE~

COPY ~spell_rev\spwi8##\spwi809.spl~     ~override~  // Simbul's Spell Trigger (previously named Spell Trigger)
  SAY NAME1 @781    SAY UNIDENTIFIED_DESC @782
COPY ~spell_rev\spwi8##\scrl9d.itm~     ~override~
  SAY NAME2 @781    SAY IDENTIFIED_DESC   @782
COPY ~spell_rev\spwi8##\spwi809d.spl~     ~override~
  SAY NAME1 @781

ADD_PROJECTILE ~spell_rev\projectles\dvicloud.pro~
COPY ~spell_rev\spwi8##\spwi810.spl~     ~override~  // Incendiary Cloud
  SAY NAME1 @783    SAY UNIDENTIFIED_DESC @784
  WRITE_SHORT 0x98 %dvicloud%
  SET dvicloud -= 1
APPEND ~clearair.2da~ ~Incendiary_Cloud                %dvicloud%~
COPY ~spell_rev\spwi8##\scrl9e.itm~     ~override~
  SAY NAME2 @783    SAY IDENTIFIED_DESC   @784
COPY ~spell_rev\spwi8##\dvicloud.eff~     ~override~

/* COPY_EXISTING ~GORLIC01.CRE~ ~override~  // Azamantes
              ~GORSKU01.CRE~ ~override~  // Flaming Skull
              ~HGSKU01.CRE~  ~override~  // Flaming Skull
  PATCH_IF (SOURCE_SIZE > 0x2d3) BEGIN
    LAUNCH_PATCH_FUNCTION ~ADD_CRE_IMMUNITY_TO_SPELL~
      INT_VAR mi_strref = 0 // no text
      STR_VAR mi_spell = ~SPWI810~ // incendiary cloud
    END
  END
  BUT_ONLY */

COPY ~spell_rev\spwi8##\spwi811.spl~     ~override~  // Symbol of Weakness (replaces Symbol, Fear)
  SAY NAME1 @785    SAY UNIDENTIFIED_DESC @786
COPY ~spell_rev\spwi8##\scrl9f.itm~     ~override~
  SAY NAME2 @785    SAY IDENTIFIED_DESC   @786
COPY ~spell_rev\shared\spwi899.spl~      ~override~ // Innate Symbol of Weakness
APPEND ~spell.ids~ ~2811 WIZARD_SYMBOL_WEAKNESS~

COPY ~spell_rev\spwi8##\spwi812.spl~     ~override~  // Abi-Dalzim's Horrid Wilting
  SAY NAME1 @787    SAY UNIDENTIFIED_DESC @788
COPY ~spell_rev\spwi8##\scrl9g.itm~     ~override~
  SAY NAME2 @787    SAY IDENTIFIED_DESC   @788
COPY ~spell_rev\spwi8##\dvhorrid.eff~     ~override~

COPY ~spell_rev\spwi8##\spwi813.spl~     ~override~  // Maze
  SAY NAME1 @789    SAY UNIDENTIFIED_DESC @790
COPY ~spell_rev\spwi8##\scrl9h.itm~     ~override~
  SAY NAME2 @789    SAY IDENTIFIED_DESC   @790

COPY ~spell_rev\spwi8##\spwi815.spl~     ~override~  // Power Word Blind
  SAY NAME1 @791    SAY UNIDENTIFIED_DESC @792
COPY ~spell_rev\spwi8##\scrl9j.itm~     ~override~
  SAY NAME2 @791    SAY IDENTIFIED_DESC   @792
COPY_EXISTING ~holdsumm.pro~ ~override~
  WRITE_SHORT 0x204 110
  WRITE_SHORT 0x206 110

COPY ~spell_rev\spwi8##\spwi816.spl~     ~override~  // Symbol of Stunning
  SAY NAME1 @793    SAY UNIDENTIFIED_DESC @794
COPY ~spell_rev\spwi8##\scrlap.itm~     ~override~
  SAY NAME2 @793    SAY IDENTIFIED_DESC   @794
/* COPY ~spell_rev\shared\spwi898.spl~      ~override~ // Innate Symbol of Stunning */

COPY ~spell_rev\spwi8##\spwi817.spl~     ~override~  // Symbol of Death
  SAY NAME1 @795    SAY UNIDENTIFIED_DESC @796
COPY ~spell_rev\spwi8##\scrlao.itm~     ~override~
  SAY NAME2 @795    SAY IDENTIFIED_DESC   @796
COPY ~spell_rev\shared\spwi897.spl~      ~override~ // Innate Symbol of Death

COPY ~spell_rev\spwi8##\spwi818.spl~     ~override~  // Bigby's Icy Grasp ("replaces" Clenched Fist)
  SAY NAME1 @797    SAY UNIDENTIFIED_DESC @798
COPY ~spell_rev\spwi8##\scrlb1.itm~     ~override~
  SAY NAME2 @797    SAY IDENTIFIED_DESC   @798
COPY ~spell_rev\spwi8##\spwi818d.spl~     ~override~
COPY ~spell_rev\spwi8##\spwi818i.eff~     ~override~
APPEND ~spell.ids~ ~2818 WIZARD_BIGBYS_ICY_GRASP~

//ADD_SPELL: Monster Summoning VIII
ADD_SPELL ~spell_rev\spwi8##\spwi819.spl~ 2 8 ~WIZARD_MONSTER_SUMMONING_6~  // Monster Summoning VIII (new mage spell)
  SAY NAME1 @868    SAY UNIDENTIFIED_DESC @869
COPY ~spell_rev\spwi8##\scrl8c.itm~     ~override~ // replaces Stone to Flesh scroll
  SAY NAME2 @868   SAY IDENTIFIED_DESC   @869
COPY ~spell_rev\spwi8##\umbhulsu.eff~     ~override~
COPY ~spell_rev\spwi8##\umbhulsu.cre~     ~override~
  SAY NAME1 @3868
  SAY NAME2 @3868
COPY ~spell_rev\spwi8##\umbhulsu.itm~     ~override~
COPY ~spell_rev\spwi8##\umbhulsu.bcs~     ~override~
COPY ~spell_rev\spwi8##\dvwi819a.bam~     ~override~
COPY ~spell_rev\spwi8##\dvwi819b.bam~     ~override~
COPY ~spell_rev\spwi8##\dvwi819c.bam~     ~override~
APPEND ~spell.ids~ ~%WIZARD_MONSTER_SUMMONING_6% WIZARD_MONSTER_SUMMONING_LEVEL_8~


/*-----------------------level 9-----------------------*/

COPY ~spell_rev\spwi9##\spwi902.spl~     ~override~  // Spell Trap
  SAY NAME1 @811    SAY UNIDENTIFIED_DESC @812
COPY ~spell_rev\spwi9##\scrl9l.itm~     ~override~
  SAY NAME2 @811    SAY IDENTIFIED_DESC   @812

/* ADD_PROJECTILE ~spell_rev\projectles\dvsplstr.pro~ */
COPY ~spell_rev\spwi9##\spwi903.spl~     ~override~  // Spellstrike
  SAY NAME1 @813    SAY UNIDENTIFIED_DESC @814
COPY ~spell_rev\spwi9##\scrl9m.itm~     ~override~
  SAY NAME2 @813    SAY IDENTIFIED_DESC   @814

COPY ~spell_rev\spwi9##\spwi905.spl~     ~override~  // Gate
  SAY NAME1 @815    SAY UNIDENTIFIED_DESC @816
COPY ~spell_rev\spwi9##\scrl9n.itm~     ~override~
  SAY NAME2 @815    SAY IDENTIFIED_DESC   @816
COPY ~spell_rev\spwi9##\spgate.eff~     ~override~
COPY ~spell_rev\spwi9##\dempitsu.cre~     ~override~
  SAY NAME1 @3815
  SAY NAME2 @3815
COPY ~spell_rev\spwi9##\dempitsu.itm~     ~override~
COPY ~spell_rev\spwi9##\dvpitsu.bcs~     ~override~

COPY ~spell_rev\spwi9##\spwi907.spl~     ~override~  // Absolute Immunity
  SAY NAME1 @817    SAY UNIDENTIFIED_DESC @818
COPY ~spell_rev\spwi9##\scrl9p.itm~     ~override~
  SAY NAME2 @817    SAY IDENTIFIED_DESC   @818

COPY ~spell_rev\spwi9##\spwi908.spl~     ~override~  // Chain Contingency
  SAY NAME1 @819    SAY UNIDENTIFIED_DESC @820
COPY ~spell_rev\spwi9##\scrl9q.itm~     ~override~
  SAY NAME2 @819    SAY IDENTIFIED_DESC   @820

COPY ~spell_rev\spwi9##\spwi909.spl~     ~override~  // Time Stop
  SAY NAME1 @821    SAY UNIDENTIFIED_DESC @822
COPY ~spell_rev\spwi9##\scrl9r.itm~     ~override~
  SAY NAME2 @821    SAY IDENTIFIED_DESC   @822

COPY ~spell_rev\spwi9##\spwi910.spl~     ~override~  // Imprisonment
  SAY NAME1 @823    SAY UNIDENTIFIED_DESC @824
COPY ~spell_rev\spwi9##\scrl9s.itm~     ~override~
  SAY NAME2 @823    SAY IDENTIFIED_DESC   @824

ADD_PROJECTILE ~spell_rev\projectles\dvmswarm.pro~
COPY ~spell_rev\spwi9##\spwi911.spl~     ~override~  // Meteor Swarm
  SAY NAME1 @825    SAY UNIDENTIFIED_DESC @826
  WRITE_SHORT 0x98 %dvmswarm%
COPY ~spell_rev\spwi9##\scrl9t.itm~     ~override~
  SAY NAME2 @825    SAY IDENTIFIED_DESC   @826
COPY ~spell_rev\spwi9##\dvmeteor.vvc~     ~override~

COPY ~spell_rev\spwi9##\spwi912.spl~     ~override~  // Power Word Kill
  SAY NAME1 @827    SAY UNIDENTIFIED_DESC @828
COPY ~spell_rev\spwi9##\scrl9u.itm~     ~override~
  SAY NAME2 @827    SAY IDENTIFIED_DESC   @828

COPY ~spell_rev\spwi9##\spwi913.spl~     ~override~  // Wail of the Banshee
  SAY NAME1 @829    SAY UNIDENTIFIED_DESC @830
COPY ~spell_rev\spwi9##\scrl9v.itm~     ~override~
  SAY NAME2 @829    SAY IDENTIFIED_DESC   @830

COPY ~spell_rev\spwi9##\spwi914.spl~     ~override~  // Larloch's Energy Drain
  SAY NAME1 @831    SAY UNIDENTIFIED_DESC @832
COPY ~spell_rev\spwi9##\scrl9w.itm~     ~override~
  SAY NAME2 @831    SAY IDENTIFIED_DESC   @832
COPY ~spell_rev\spwi9##\dvenerdr.eff~     ~override~

COPY ~spell_rev\spwi9##\spwi915.spl~     ~override~  // Black Blade of Disaster
  SAY NAME1 @833    SAY UNIDENTIFIED_DESC @834
COPY ~spell_rev\spwi9##\scrl9x.itm~     ~override~
  SAY NAME2 @833    SAY IDENTIFIED_DESC   @834
COPY ~spell_rev\spwi9##\blakblad.itm~     ~override~
COPY ~spell_rev\spwi9##\blakblad.spl~     ~override~

COPY ~spell_rev\spwi9##\spwi916.spl~     ~override~  // Shapechange
  SAY NAME1 @835    SAY UNIDENTIFIED_DESC @836
COPY ~spell_rev\spwi9##\scrl9y.itm~     ~override~
  SAY NAME2 @835    SAY IDENTIFIED_DESC   @836
COPY ~spell_rev\spwi9##\spwi971.itm~     ~override~
COPY ~spell_rev\spwi9##\spwi971.spl~     ~override~
  PATCH_IF GAME_IS ~iwdee~ BEGIN SAY NAME1 @21007 END
COPY ~spell_rev\spwi9##\spwi972.itm~     ~override~
COPY ~spell_rev\spwi9##\spwi972.spl~     ~override~
  PATCH_IF GAME_IS ~iwdee~ BEGIN SAY NAME1 @21008 END
COPY ~spell_rev\spwi9##\spwi973.itm~     ~override~
COPY ~spell_rev\spwi9##\spwi973.spl~     ~override~
  PATCH_IF GAME_IS ~iwdee~ BEGIN SAY NAME1 @21009 END
COPY ~spell_rev\spwi9##\spwi974.itm~     ~override~
COPY ~spell_rev\spwi9##\spwi974.spl~     ~override~
  PATCH_IF GAME_IS ~iwdee~ BEGIN SAY NAME1 @21010 END
COPY ~spell_rev\spwi9##\spwi975.itm~     ~override~
COPY ~spell_rev\spwi9##\spwi975.spl~     ~override~
  SAY NAME1 @21006
COPY ~spell_rev\spwi9##\spwi976.spl~     ~override~
  PATCH_IF GAME_IS ~iwdee~ BEGIN SAY NAME1 @21011 END
COPY ~spell_rev\spwi9##\spwi976.itm~     ~override~

COPY ~spell_rev\spwi9##\spwi917.spl~     ~override~  // Freedom
  SAY NAME1 @837 SAY UNIDENTIFIED_DESC @838

COPY ~spell_rev\spwi9##\scrl9z.itm~     ~override~
  SAY NAME2 @837    SAY IDENTIFIED_DESC   @838

COPY ~spell_rev\spwi9##\spwi918.spl~     ~override~  // Bigby's Crushing Hand
  SAY NAME1 @839    SAY UNIDENTIFIED_DESC @840
COPY ~spell_rev\spwi9##\scrlb2.itm~     ~override~
  SAY NAME2 @839    SAY IDENTIFIED_DESC   @840
COPY ~spell_rev\spwi9##\spwi918d.spl~     ~override~

COPY ~spell_rev\spwi9##\spwi919.spl~     ~override~  // Wish
  SAY NAME1 @841    SAY UNIDENTIFIED_DESC @842
COPY ~spell_rev\spwi9##\scrlb4.itm~     ~override~
  SAY NAME2 @841    SAY IDENTIFIED_DESC   @842
COPY ~spell_rev\spwi9##\spwish38.spl~     ~override~  // Mass Breach

COPY ~spell_rev\spwi9##\p3-12m4.itm~     ~override~

/*
//ADD_SPELL: Monster Summoning IX
ADD_SPELL ~spell_rev\spwi9##\spwi906.spl~ 2 9 ~WIZARD_MONSTER_SUMMONING_7~  // Monster Summoning IX (new mage spell)
  SAY NAME1 @870    SAY UNIDENTIFIED_DESC @871
COPY ~spell_rev\spwi9##\dvwi906s.itm~     ~override~  // new scroll
  SAY NAME2 @870    SAY IDENTIFIED_DESC   @871
COPY ~spell_rev\spwi9##\basilgsu.eff~     ~override~
COPY ~spell_rev\spwi9##\basilgsu.cre~     ~override~
COPY ~spell_rev\spwi9##\basilgsu.bcs~     ~override~
COPY ~spell_rev\spwi9##\basilg1.itm~     ~override~
COPY ~spell_rev\spwi9##\basilg2.itm~     ~override~
COPY ~spell_rev\spwi9##\basilg3.itm~     ~override~
COPY ~spell_rev\spwi9##\dvwi906a.bam~    ~override~
COPY ~spell_rev\spwi9##\dvwi906b.bam~    ~override~
COPY ~spell_rev\spwi9##\dvwi906c.bam~    ~override~
APPEND ~spell.ids~ ~%WIZARD_MONSTER_SUMMONING_7% WIZARD_MONSTER_SUMMONING_LEVEL_9~
*/


/*-----------------------level 10-----------------------*/

COPY ~spell_rev\spwi9##\spwi920.spl~     ~override~  // Energy Blades
  SAY NAME1 @851    SAY UNIDENTIFIED_DESC @852
COPY ~spell_rev\spwi9##\eneblade.itm~     ~override~
  SAY UNIDENTIFIED_DESC @1024

COPY ~spell_rev\spwi9##\spwi921.spl~     ~override~  // Improved Alacrity
  SAY NAME1 @853    SAY UNIDENTIFIED_DESC @854

COPY ~spell_rev\spwi9##\spwi922.spl~     ~override~  // Dragon's Breath
  SAY NAME1 @855    SAY UNIDENTIFIED_DESC @856

COPY ~spell_rev\spwi9##\spwi923.spl~     ~override~  // Summon Planetar
  SAY NAME1 @857    SAY UNIDENTIFIED_DESC @858
COPY ~spell_rev\spwi9##\plangood.cre~     ~override~
  SAY NAME1 @3857
  SAY NAME2 @3857
COPY ~spell_rev\spwi9##\dvplang.bcs~     ~override~
COPY ~spell_rev\spwi9##\dvplanga.itm~     ~override~
COPY ~spell_rev\spwi9##\dvplangr.itm~     ~override~
COPY ~spell_rev\spwi9##\dvplangw.itm~     ~override~

COPY ~spell_rev\spwi9##\dw#plang.spl~     ~override~  // SCSII Planetar

COPY ~spell_rev\spwi9##\spwi924.spl~     ~override~  // Summon Dark Planetar
  SAY NAME1 @859    SAY UNIDENTIFIED_DESC @860
COPY ~spell_rev\spwi9##\planevil.cre~     ~override~
  SAY NAME1 @3859
  SAY NAME2 @3859
COPY ~spell_rev\spwi9##\dvplane.bcs~     ~override~
COPY ~spell_rev\spwi9##\dvplanea.itm~     ~override~
COPY ~spell_rev\spwi9##\dvplaner.itm~     ~override~
COPY ~spell_rev\spwi9##\dvplanew.itm~     ~override~

COPY ~spell_rev\spwi9##\dw#plane.spl~     ~override~  // SCSII Dark Planetar

COPY ~spell_rev\spwi9##\spwi925.spl~     ~override~  // Comet
  SAY NAME1 @861    SAY UNIDENTIFIED_DESC @862


/*------------Manage ADD_SPELL References, Part 2-----------*/

// This function goes through the SPL/ITM/EFF files in the game and replaces references
// to our temp filenames with references to the final filenames assigned by ADD_SPELL.
LAF ASSIGN_FINAL_NAMES_FOR_NEW_SPELL_REFERENCES END


/*---------------------Spell Shield fix---------------------*/

INCLUDE ~spell_rev\lib\ardanis_spell_shield.tph~
LAF ardanis_spell_shield END


/*---------------------Custom Sec Types---------------------*/

INCLUDE ~spell_rev\lib\kreso_haste_slow.tph~
INCLUDE ~spell_rev\lib\kreso_petrification.tph~
INCLUDE ~spell_rev\lib\dispelling_screen.tph~
INCLUDE ~spell_rev\lib\insects.tph~   // insect removal thingie
INCLUDE ~spell_rev\lib\refinements.tph~  // refinements spells reverted back to SR, won't parse unless Refinements is already there

//Imprisonment patches.
INCLUDE "%MOD_FOLDER%/lib/imprisonment.tph"

//True sight patches.
INCLUDE "%MOD_FOLDER%/lib/inquisitor_true_seeing.tph"

//// SECTYPE FIXES FOR VANILLA MESS and some more//

INCLUDE ~spell_rev\lib\kreso_extra.tph~

////////////////////////KILL DOUBLE STRINGS ON SPELL REMOVALS IT HURTS MY EYES///////////
ACTION_IF  FILE_EXISTS_IN_GAME ~spwi513b.spl~ BEGIN
COPY_EXISTING ~spwi513b.spl~ ~override~
LPF DELETE_SPELL_EFFECT INT_VAR opcode_to_delete = 139 END
 END

ACTION_IF  FILE_EXISTS_IN_GAME ~spwi805b.spl~ BEGIN
COPY_EXISTING ~spwi805b.spl~ ~override~
LPF DELETE_SPELL_EFFECT INT_VAR opcode_to_delete = 139 END
 END

ACTION_IF  FILE_EXISTS_IN_GAME ~spwi903b.spl~ BEGIN
COPY_EXISTING ~spwi903b.spl~ ~override~
LPF DELETE_SPELL_EFFECT INT_VAR opcode_to_delete = 139 END
 END

/// EE COMPONENT//
ACTION_IF FILE_EXISTS_IN_GAME ~concentr.2da~ BEGIN // EE v2.0+
INCLUDE ~spell_rev\lib\kreso_ee.tph~
INCLUDE ~spell_rev\lib\kreso_eestatsr.tph~
END


/*---------------------Tutu Scrolls---------------------*/

ACTION_IF (GAME_IS ~tutu tutu_totsc~) BEGIN
  ACTION_FOR_EACH scroll IN
    ~scrl1b~ // agannazar's scorcher
    ~scrl67~ // armor
    ~scrl71~ // blindness
    ~scrl85~ // blur
    ~scrl68~ // burning hands
    ~scrl5e~ // champion's strength
    ~scrl5p~ // chaos
    ~scrl5f~ // chaotic commands
    ~scrl69~ // charm person
    ~scrl82~ // chill touch
    ~scrl83~ // chromatic orb
    ~scrl1d~ // clairvoyance
    ~scrl2e~ // cloudkill
    ~scrl70~ // color spray
    ~scrl1u~ // confusion
    ~scrl56~ // cure serious wounds
    ~scrl5b~ // defensive harmony
    ~scrl86~ // detect evil
    ~scrl87~ // detect invisibility
    ~scrl1v~ // dimension door
    ~scrl1s~ // dire charm
    ~scrl1e~ // dispel magic
    ~scrl5n~ // domination
    ~scrl5h~ // emotion
    ~scrl5q~ // feeblemind
    ~scrl1g~ // fireball
    ~scrl1f~ // flame arrow
    ~scrl58~ // free action
    ~scrl72~ // friends
    ~scrl1t~ // ghost armor
    ~scrl1c~ // ghoul touch
    ~scrl66~ // grease
    ~scrl5i~ // greater malison
    ~scrl1h~ // haste
    ~scrl5o~ // hold monster
    ~scrl1i~ // hold person
    ~scrl89~ // horror
    ~scrl1y~ // improved invisibility
    ~scrl76~ // infravision
    ~scrl90~ // invisibility
    ~scrl91~ // knock
    ~scrl92~ // know opponent
    ~scrl84~ // larloch's minor drain
    ~scrl1k~ // lightning bolt
    ~scrl93~ // luck
    ~scrl77~ // magic missile
    ~scrl95~ // melf's acid arrow
    ~scrl5a~ // mental domination
    ~scrl1z~ // minor globe of invulnerability
    ~scrl96~ // mirror image
    ~scrl1l~ // monster summoning i
    ~scrl2a~ // monster summoning ii
    ~scrl2g~ // monster summoning iii
    ~scrl59~ // neutralize poison
    ~scrl1m~ // non-detection
    ~scrl5j~ // otiluke's resilient sphere
    ~scrl5m~ // polymorph self
    ~scrl78~ // protection from evil
    ~scrl1n~ // protection from normal missiles
    ~scrl73~ // protection from petrification
    ~scrl03~ // protection from acid
    ~scrl04~ // protection from cold
    ~scrl05~ // protection from electricity
    ~scrl5d~ // protection from evil 10' radius
    ~scrl06~ // protection from fire
    ~scrl5c~ // protection from lightning
    ~scrl07~ // protection from magic
    ~scrl15~ // protection from petrification
    ~scrl08~ // protection from poison
    ~scrl09~ // protection from undead
    ~scrl5g~ // remove curse
    ~scrl94~ // resist fear
    ~scrl79~ // shield
    ~scrl80~ // shocking grasp
    ~scrl1p~ // skull trap
    ~scrl81~ // sleep
    ~scrl1o~ // slow
    ~scrl5k~ // spirit armor
    ~scrl97~ // stinking cloud
    ~scrl98~ // strength
    ~scrl1q~ // vampiric touch
    ~scrl3g~ // vocalize
    ~scrl99~ // web
  BEGIN
    ACTION_IF (FILE_EXISTS_IN_GAME ~%scroll%.itm~) BEGIN
      COPY_EXISTING ~%scroll%.itm~ ~override/_%scroll%.itm~
    END
  END
END


/*----------------Add New Spell Scrolls

COPY_EXISTING ~ribald3.sto~ ~override~ // Ribald's Secret Stash
  PATCH_IF (SOURCE_SIZE > 0x9b) BEGIN
    ADD_STORE_ITEM ~scrlw801~ AFTER ~scrl9v~ #1 #1 #0 ~IDENTIFIED~ #1 // Adds 1 Ghostform Scroll
  END
  BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING ~25spell.sto~ ~override~ // Arcana Archives
  PATCH_IF (SOURCE_SIZE > 0x9b) BEGIN
    ADD_STORE_ITEM ~scrlw801~ AFTER ~scrlb1~ #1 #0 #0 ~IDENTIFIED~ #2 // Adds 2 Ghostform Scrolls
  END
  BUT_ONLY_IF_IT_CHANGES-----------------*/

// added by SubtleDoctor:
/*------ SET ARCANE SPELL SCHOOLS ------*/

// and mark arcane spells for spellbook removal 

INCLUDE ~spell_rev/lib/d5_spell_school_list.tpa~
INCLUDE ~spell_rev/lib/d5_set_spell_schools.tpa~
LAF set_spell_schools END

// EE spell flags.
ACTION_IF (GAME_IS ~bgee bg2ee eet iwdee~) BEGIN
    INCLUDE ~spell_rev/lib/handle_spell_flags.tph~
    LAF ee_handle_spell_flags END
END

/*------------ MODIFY IR STUFF ------------*/

ACTION_IF (FILE_CONTAINS_EVALUATED (~SPELL.IDS~ ~[ %TAB%]CLERIC_POLYMORPH_OTHER[ %TAB%%LNL%%MNL%%WNL%]~)) BEGIN // Periapt of Form Stability Druid Polymorph Other
  LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~CLERIC_POLYMORPH_OTHER~ RET spell_res END
  OUTER_SPRINT polymorph_other ~%spell_res%~
  ACTION_IF (FILE_EXISTS_IN_GAME ~amul24.itm~) THEN BEGIN
    COPY_EXISTING ~amul24.itm~ ~override~
      LPF CLONE_EFFECT INT_VAR silent = 1 match_opcode = 206 STR_VAR match_resource = ~spwi415~ resource = EVAL ~%polymorph_other%~ END
    IF_EXISTS BUT_ONLY
  END
END

ACTION_IF (MOD_IS_INSTALLED ~item_rev.tp2~ ~0~) BEGIN

  ACTION_IF (FILE_EXISTS_IN_GAME ~brac23.itm~) THEN BEGIN
	ACTION_IF (TRA_ENTRY_EXISTS (~10057~ ~spell_rev\languages\%LANGUAGE%\divine.tra~)) BEGIN
	  COPY_EXISTING ~brac23.itm~ ~override~
		SPRINT old_spell_name @10057 			// Righteous Magic
		SPRINT new_spell_name @57 				// Righteous Fury
	    READ_LONG 0x54 "valid"
	    PATCH_IF ("%valid%" < 2147483646) AND ("%valid%" >= 0) BEGIN 
	    	READ_STRREF 0x54 "description"
	    	INNER_PATCH_SAVE new_desc ~%description%~ BEGIN
	          REPLACE_TEXTUALLY ~%old_spell_name%~ ~%new_spell_name%~
	    	END
	    	SAY_EVALUATED 0x54 ~%new_desc%~
	    END
	  BUT_ONLY
	END
	ACTION_IF (FILE_EXISTS_IN_GAME ~brac23.spl~) THEN BEGIN
	  COPY_EXISTING ~brac23.spl~ ~override~
		SAY NAME1 @57 							// Righteous Fury
	  BUT_ONLY
	END
  END

  ACTION_IF (FILE_EXISTS_IN_GAME ~misc3a5.itm~) THEN BEGIN
	ACTION_IF (TRA_ENTRY_EXISTS (~10721~ ~spell_rev\languages\%LANGUAGE%\arcane.tra~)) BEGIN
	  COPY_EXISTING ~misc3a5.itm~ ~override~
		SPRINT old_spell_name @10721 			// Spell Turning
		SPRINT new_spell_name @721 				// Greater Spell Deflection
	    READ_LONG 0x54 "valid"
	    PATCH_IF ("%valid%" < 2147483646) AND ("%valid%" >= 0) BEGIN 
	    	READ_STRREF 0x54 "description"
	    	INNER_PATCH_SAVE new_desc ~%description%~ BEGIN
	          REPLACE_TEXTUALLY ~%old_spell_name%~ ~%new_spell_name%~
	    	END
	    	SAY_EVALUATED 0x54 ~%new_desc%~
	    END
	  BUT_ONLY
	END
  END

// also, do this to misc3a, misc3a1-a8 - the other pages of the Book
  ACTION_FOR_EACH book IN ~misc3a~ ~misc3a1~ ~misc3a2~ ~misc3a3~ ~misc3a4~ ~misc3a5~ ~misc3a6~ ~misc3a7~ ~misc3a8~ BEGIN
	COPY_EXISTING ~%book%~ ~override~
	  LPF ALTER_EFFECT INT_VAR match_opcode = 122 STR_VAR match_resource = ~misc3a9~ resource = ~misc3a3~ END
	IF_EXISTS BUT_ONLY
  END

  ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h65.itm~) THEN BEGIN
	ACTION_IF (TRA_ENTRY_EXISTS (~10175~ ~spell_rev\languages\%LANGUAGE%\divine.tra~)) BEGIN
	  COPY_EXISTING ~sw1h65.itm~ ~override~
		SPRINT old_spell_name @10175 			// Draw Upon Holy Might
		SPRINT new_spell_name @175 				// Draw Upon Divine Might
	    READ_LONG 0x54 "valid"
	    PATCH_IF ("%valid%" < 2147483646) AND ("%valid%" >= 0) BEGIN 
	    	READ_STRREF 0x54 "description"
	    	INNER_PATCH_SAVE new_desc ~%description%~ BEGIN
	          REPLACE_TEXTUALLY ~%old_spell_name%~ ~%new_spell_name%~
	    	END
	    	SAY_EVALUATED 0x54 ~%new_desc%~
	    END
	  BUT_ONLY
	END
  END

END

// Last batch of fixes: patch Display Text [139] with correct string refs.
// This is for BG1EE only, so wrapped in an ACTION_IF block.
//
// Depends only on the main copy block and having resource references resolved,
// so can be moved up in the main component if needed.
ACTION_IF (ENGINE_IS ~bgee~) BEGIN
  INCLUDE ~spell_rev/lib/fix_displayed_strings.tph~
  LAF fix_displayed_strrefs END
END
