//Libraries.
INCLUDE "%WEIDU_LIBRARY_DIR%/components.tpa"


//Set variables.
OUTER_TEXT_SPRINT root "%MOD_FOLDER%/components/main"

//Execute subcomponents.
//Install spell symbols.
LAF install_subcomponent STR_VAR
    subcomponent = "%root%/subcomponents/spell_symbols.tpa"
END

//Install sectypes.
LAF install_subcomponent STR_VAR
    subcomponent = "%root%/subcomponents/sectypes.tpa"
END

//Install vvcs needed by spells, e.g. via Play Visual [215] opcode.
LAF install_subcomponent STR_VAR
    subcomponent = "%root%/subcomponents/vvcs.tpa"
END

//Install projectiles.
LAF install_subcomponent STR_VAR
    subcomponent = "%root%/subcomponents/projectiles.tpa"
END

//Install icons for spells.
LAF install_subcomponent STR_VAR
    subcomponent = "%root%/subcomponents/icons.tpa"
END

//Install tables for spells (e. g. tables used by Select Spell [214] opcode).
LAF install_subcomponent STR_VAR
    subcomponent = "%root%/subcomponents/tables.tpa"
END

//Install items for spells (e. g. items created through spells).
LAF install_subcomponent STR_VAR
    subcomponent = "%root%/subcomponents/items.tpa"
END
